#服务端口
server:
  port: 8006
spring:
  application:
    name: service-ucenter
  profiles:
    active: dev
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gxschool?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr:
          127.0.0.1:8848
mybatis-plus:
  mapper-locations: classpath:cn/GnaixEuy/ucenter/mapper/xml/*.xml
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #默认的连接超时时间1秒,若1秒没有返回数据,自动的触发降级逻辑
            timeoutInMilliseconds: 6000
# 设置日志级别
logging:
  level:
    root: warn
